const actionTypes = {
  LOAD_USER: 'LOAD_USER',
  LOAD_USER_ERROR: 'LOAD_USER_ERROR',
  LOAD_SPOT: 'LOAD_SPOT',
  LOAD_SPOT_ERROR: 'LOAD_SPOT_ERROR',
  LOAD_SPOTS: 'LOAD_SPOTS',
  LOAD_SPOTS_ERROR: 'LOAD_SPOTS_ERROR',
  LOGIN_USER_GOOGLE: 'LOGIN_USER_GOOGLE',
  LOGIN_ERROR: 'LOGIN_ERROR',

};
export default actionTypes;
